### ISSUE TITLE
[tensorboardX==1.7] TypeError: __init__() got an unexpected keyword argument 'log_dir'

### ISSUE THREAD

**Issue by gianderiu** [lanpa/tensorboardX#447]
After upgrading from 1.6 to 1.7 I got this error:
```
celery_1                   | [2019-06-06 10:37:21,940: ERROR/Process-2:1] Process Process-2:1
celery_1                   | Traceback (most recent call last):
celery_1                   |   File "/usr/local/lib/python3.6/dist-packages/billiard/process.py", line 327, in _bootstrap
celery_1                   |     self.run()
celery_1                   |   File "/usr/local/lib/python3.6/dist-packages/billiard/process.py", line 114, in run
celery_1                   |     self._target(*self._args, **self._kwargs)
celery_1                   |   File "/opt/www/celer/tasks.py", line 34, in start_training
celery_1                   |     training = TrainRunner(experiment_id=designpoint_id, project_id=project_id, experiment_path=exp_path )
celery_1                   |   File "/opt/www/api/engine/network/TrainRunner.py", line 53, in __init__
celery_1                   |     self.tbx_writer = SummaryWriter(log_dir=os.path.join(experiment_path, 'runs/%s' % tbx_name))
celery_1                   |   File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 254, in __init__
celery_1                   |     self._get_file_writer()
celery_1                   |   File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 310, in _get_file_writer
celery_1                   |     self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
celery_1                   | TypeError: __init__() got an unexpected keyword argument 'log_dir'
```
downgrading back to 1.6 solved the problem.

**Comment by lanpa** [comment]
Shouldn't that be `logdir` instead of `log_dir`?

**Comment by gianderiu** [comment]
OK, thank you
just found the difference:
v1.6 (log_dir): https://tensorboardx.readthedocs.io/en/v1.6/tensorboard.html#tensorboardX.SummaryWriter.__init__
v1.7 (logdir): https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.__init__

**Comment by lanpa** [comment]
Oh, sorry for the inconvenience. Updated the release note.

https://github.com/lanpa/tensorboardX/releases/tag/v1.7

Thanks for digging that out.
